production:
  adapter: postgresql
  encoding: unicode
  database: harriscitrus_production
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  
development:
  adapter: postgresql
  encoding: unicode
  database: harriscitrus_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  
test:
  adapter: postgresql
  encoding: unicode
  database: harriscitrus_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432